export const WebRoutes = {
  DASHBOARD: "/",
  CATEGORY: "/categories",
  CENTERS: "/our-centers",
  RECOMMENDATION: "/recommendations",
  ABOUT_US: "/about-Us",
  CONTACT_US: "/contact-us",
  BLOG: "/blogs",
  RESULTS: "/results",
  IMPORTANT_LINKS: "/important-links",
  DEMO_VIDEO: "/demo-videos",
  OBJECTIVE: "/objectives",
  PHOTO_GALLARY: "/gallary",
  VIDEO_GALLARY: "/video-gallary",
  GALLARY_GRID: "/gallaryList/",
  MEDIA: "/media",
  CAREER: "/careers",
  CAREER_DETAILS: "/careers-details/",
  PRIVACY_POLICY: "/privacy-policy",
  DISCLAIMER: "/disclaimer",
  TERMS_SERVICE: "/terms-and-conditions",
};
